# Config file for tools installation and setup

# tool: -Name of the YAML entry.
#   name: "tmux" -Name of the tool.
#   filename: "tmux" -Name of the filename available at the src dir.
#   paths: -Paths for the tool setup.
#     src: "../toolbox/tmux/" -Source path for the tool.
#     dst: "~/.local/des/bin/" -Destination path for the tool.

tools:
  - tmux:
      name: "tmux"
      filename: "tmux"
      paths:
        - src: "$TOOLBOX/tmux/"
        - dst: "$DOTFILES/bin/"

  - nvim:
      name: "nvim"
      filename: "nvim"
      paths:
        - src: "$TOOLBOX/nvim/bin"
        - dst: "$DOTFILES/bin/"

  - rg:
      name: "rg"
      filename: "rg"
      paths:
        - src: "$TOOLBOX/ripgrep/"
        - dst: "$DOTFILES/bin/"
  
  - fd:
      name: "fd"
      filename: "fd"
      paths:
        - src: "$TOOLBOX/fd/"
        - dst: "$DOTFILES/bin/"

  - bat:
      name: "bat"
      filename: "bat"
      paths:
        - src: "$TOOLBOX/bat/"
        - dst: "$DOTFILES/bin/"
          
  - vivid:
      name: "vivid"
      filename: "vivid"
      paths:
        - src: "$TOOLBOX/vivid/"
        - dst: "$DOTFILES/bin/"
